// Use the installed Google Generative AI SDK
const { GoogleGenerativeAI } = require('@google/generative-ai');
const { randomUUID } = require('crypto');
const { promisePool } = require('../config/db'); // Correct MySQL pool

const GEMINI_DEFAULT = process.env.GEMINI_MODEL || 'gemini-2.5-flash';

// Simple in-memory circuit breaker to avoid pounding an overloaded model
const CIRCUIT_BREAKER_THRESHOLD = Number(process.env.GEMINI_CB_THRESHOLD) || 5; // consecutive 503s
const CIRCUIT_BREAKER_RESET_MS = Number(process.env.GEMINI_CB_RESET_MS) || 60_000; // 1 minute
let consecutiveFailures = 0;
let circuitOpenUntil = 0;

/**
 * Helper to call Gemini API
 */
const callGemini = async (message, model, apiKey) => {
  const chosen = model || GEMINI_DEFAULT;
  const genai = new GoogleGenerativeAI(apiKey);

  const modelInstance = genai.getGenerativeModel({
    model: chosen,
    generationConfig: {
      temperature: 0.3,
      maxOutputTokens: 8000,
    },
  });

  const result = await modelInstance.generateContent({
    contents: [{ parts: [{ text: message }] }],
  });

  const data = result?.response;

  if (data?.candidates?.length) {
    const textParts = data.candidates
      .map(c => {
        const parts = c?.content?.parts || [];
        return parts
          .map(p => p?.text || p?.executableCode?.code || p?.codeExecutionResult?.output || '')
          .join('');
      })
      .filter(t => t && t.trim().length > 0);

    if (textParts.length > 0) return textParts.join('\n');
  }

  if (typeof data?.text === 'function') {
    try {
      const helperText = data.text();
      if (helperText && helperText.trim().length > 0) return helperText;
    } catch (e) {
      console.warn('Gemini response.text() helper threw:', e.message);
    }
  }

  try {
    console.debug('Gemini raw response:', JSON.stringify(data, null, 2));
  } catch (e) {
    console.debug('Gemini raw response (stringify failed):', data);
  }

  return "⚠️ No response generated by Gemini. Please try again.";
};

/**
 * Retry Gemini API if overloaded
 */
const retryCallGemini = async (message, model, apiKey, retries = 5, baseDelay = 1000) => {
  // If circuit is open, short-circuit immediately
  if (circuitOpenUntil && Date.now() < circuitOpenUntil) {
    const waitSec = Math.ceil((circuitOpenUntil - Date.now()) / 1000);
    const err = new Error(`Gemini service temporarily unavailable (circuit open, try again in ${waitSec}s)`);
    err.isCircuitOpen = true;
    throw err;
  }

  for (let i = 0; i < retries; i++) {
    try {
      const result = await callGemini(message, model, apiKey);
      // success -> reset failure counter and close circuit
      consecutiveFailures = 0;
      circuitOpenUntil = 0;
      return result;
    } catch (err) {
      const status = err.response?.status;

      // If service overloaded (503) then increment failure counter
      if (status === 503) {
        consecutiveFailures += 1;
        console.warn(`Gemini overloaded (attempt ${i + 1}/${retries}). Consecutive 503s: ${consecutiveFailures}`);

        // Trip circuit if threshold reached
        if (consecutiveFailures >= CIRCUIT_BREAKER_THRESHOLD) {
          circuitOpenUntil = Date.now() + CIRCUIT_BREAKER_RESET_MS;
          console.warn(`Gemini circuit opened for ${CIRCUIT_BREAKER_RESET_MS / 1000}s due to repeated 503s`);
          const circuitErr = new Error('Gemini service temporarily unavailable (circuit opened)');
          circuitErr.isCircuitOpen = true;
          throw circuitErr;
        }

        // exponential backoff with jitter
        const backoff = Math.min(baseDelay * Math.pow(2, i), 30_000);
        const jitter = Math.floor(Math.random() * 1000);
        const waitMs = backoff + jitter;
        console.warn(`Retrying Gemini in ${Math.round(waitMs / 1000 * 10) / 10}s (backoff + jitter)`);
        await new Promise(r => setTimeout(r, waitMs));
        // continue to next retry
      } else {
        // non-retriable or other error -> rethrow
        throw err;
      }
    }
  }

  // ran out of retries
  const err = new Error('Gemini service unavailable after retries');
  err.response = { status: 503 };
  throw err;
};

/**
 * Handle Gemini chat requests
 */
exports.geminiChat = async (req, res) => {
  try {
    const { message, model, user_id } = req.body || {};
    if (!message || !message.trim()) {
      return res.status(400).json({ success: false, message: 'Missing `message` in request body' });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(503).json({ success: false, message: 'GEMINI_API_KEY not configured' });
    }

    try {
      const reply = await retryCallGemini(message.trim(), model, apiKey);

      // Save chat to MySQL
      const sessionId = req.body?.session_id || randomUUID();
      try {
        await promisePool.query(
          'INSERT INTO career_chats (user_id, session_id, query, response) VALUES (?, ?, ?, ?)',
          [user_id || null, sessionId, message, reply]
        );
      } catch (dbErr) {
        console.error('Failed to save chat to DB:', dbErr?.message || dbErr);
      }

      return res.json({ success: true, reply, model: model || GEMINI_DEFAULT, session_id: sessionId });
    } catch (error) {
      console.error('Gemini API Error:', error?.response?.data || error.message);
      console.error(error);

      // If circuit breaker opened, return a friendly 503 immediately
      if (error.isCircuitOpen) {
        return res.status(503).json({ success: false, message: 'Gemini service is temporarily unavailable due to high load. Please try again in a minute.' });
      }

      // fallback model
      if ((error.response?.status === 404 || error.response?.status === 503) && model !== 'text-bison-001') {
        try {
          const fallbackReply = await retryCallGemini(message.trim(), 'text-bison-001', apiKey);
          const sessionId = req.body?.session_id || randomUUID();
          await promisePool.query(
            'INSERT INTO career_chats (user_id, session_id, query, response) VALUES (?, ?, ?, ?)',
            [user_id || null, sessionId, message, fallbackReply]
          );
          return res.json({
            success: true,
            reply: fallbackReply,
            fallback: true,
            fallbackModel: 'text-bison-001',
            session_id: sessionId,
          });
        } catch (fallbackErr) {
          console.error('Fallback model also failed:', fallbackErr.message);
          throw fallbackErr;
        }
      }

      throw error;
    }
  } catch (err) {
    console.error('Gemini Controller Error:', err.message);
    console.error(err);
    res.status(502).json({
      success: false,
      message: 'Failed to contact Gemini API. Check API key or model name.',
    });
  }
};

/**
 * Get user's chat history
 */
exports.getChatHistory = async (req, res) => {
  const { user_id } = req.query;

  try {
    const [rows] = await promisePool.query(
      'SELECT * FROM career_chats WHERE user_id = ? ORDER BY created_at DESC',
      [user_id || null]
    );

    res.status(200).json({ success: true, history: rows });
  } catch (error) {
    console.error('Error fetching chat history:', error.message);
    console.error(error);
    res.status(500).json({ success: false, message: 'Error fetching chat history' });
  }
};

/**
 * Delete chat session (UUID-safe + null-safe)
 */
exports.deleteChatSession = async (req, res) => {
  let query, params;
  try {
    const { session_id, user_id } = req.body || {};
    if (!session_id) return res.status(400).json({ success: false, message: 'Missing session_id' });

    // Normalize to array so we support bulk delete. session_id can be a single
    // value or an array of values. Values may be numeric (id) or string (session_id UUID).
    const ids = Array.isArray(session_id) ? session_id : [session_id];
    const numericIds = ids.filter(id => /^[0-9]+$/.test(String(id))).map(Number);
    const stringIds = ids.filter(id => !(/^[0-9]+$/.test(String(id))));

    const clauses = [];
    const paramsAll = [];

    if (numericIds.length > 0) {
      const placeholders = numericIds.map(() => '?').join(',');
      clauses.push(`id IN (${placeholders})`);
      paramsAll.push(...numericIds);
    }

    if (stringIds.length > 0) {
      const placeholders = stringIds.map(() => '?').join(',');
      // Cast DB column to CHAR to be robust against numeric-typed columns
      clauses.push(`CAST(session_id AS CHAR) IN (${placeholders})`);
      paramsAll.push(...stringIds);
    }

    if (clauses.length === 0) {
      return res.status(400).json({ success: false, message: 'No valid ids provided' });
    }

    // Build final query and include user restriction
    let whereClause = `(${clauses.join(' OR ')})`;
    if (user_id !== undefined && user_id !== null) {
      whereClause += ' AND user_id = ?';
      paramsAll.push(user_id);
    } else {
      whereClause += ' AND user_id IS NULL';
    }

    query = `DELETE FROM career_chats WHERE ${whereClause}`;
    const [result] = await promisePool.query(query, paramsAll);
    return res.json({ success: true, message: 'Session(s) deleted', affectedRows: result.affectedRows });
  } catch (err) {
    console.error('Error deleting chat session:', err.message || err);
    // Log SQL and params to help debugging if deletion still fails
    console.error('Chat session delete failed. SQL:', query, 'params:', params);
    return res.status(500).json({ success: false, message: 'Failed to delete session' });
  }
};

